interface AttendanceRecord {
  id: string;
  employeeId: string;
  employeeName: string;
  employeeIdNumber: string;
  designation: string;
  date: string;
  inTime: string;
  outTime: string;
  workingHours: number;
  status: "Present" | "Absent" | "Late" | "Half-day" | "Leave";
  createdAt: string;
  autoGenerated?: boolean;
}

const STORAGE_KEY = "dob_attendance";

export function getAllAttendanceRecords(): AttendanceRecord[] {
  const stored = localStorage.getItem(STORAGE_KEY);
  return stored ? JSON.parse(stored) : [];
}

export function getTodayAttendanceRecord(employeeId: string): AttendanceRecord | null {
  const today = new Date().toISOString().slice(0, 10);
  const records = getAllAttendanceRecords();
  return records.find(r => r.employeeId === employeeId && r.date === today) || null;
}

export function getAttendanceRecordByDate(employeeId: string, date: string): AttendanceRecord | null {
  const records = getAllAttendanceRecords();
  return records.find(r => r.employeeId === employeeId && r.date === date) || null;
}

export function calculateWorkingHours(inTime: string, outTime: string): number {
  if (!inTime || !outTime) return 0;
  
  const [inHour, inMin] = inTime.split(":").map(Number);
  const [outHour, outMin] = outTime.split(":").map(Number);
  
  const inMinutes = inHour * 60 + inMin;
  const outMinutes = outHour * 60 + outMin;
  
  const diff = outMinutes - inMinutes;
  return Math.max(0, diff / 60);
}

export function isLate(inTime: string, officeStartTime: string): boolean {
  if (!inTime || !officeStartTime) return false;
  
  const [inHour, inMin] = inTime.split(":").map(Number);
  const [startHour, startMin] = officeStartTime.split(":").map(Number);
  
  const inMinutes = inHour * 60 + inMin;
  const startMinutes = startHour * 60 + startMin;
  
  return inMinutes > startMinutes;
}

export function getAutoStatus(inTime: string, workingHours: number, officeStartTime: string): AttendanceRecord["status"] {
  if (workingHours === 0) return "Absent";
  if (isLate(inTime, officeStartTime)) return "Late";
  if (workingHours < 4) return "Half-day";
  return "Present";
}

export function createOrUpdateAttendanceRecord(
  employeeId: string,
  employeeName: string,
  employeeIdNumber: string,
  designation: string,
  updates: Partial<AttendanceRecord>,
  officeStartTime: string = "08:00"
): AttendanceRecord {
  const today = new Date().toISOString().slice(0, 10);
  const records = getAllAttendanceRecords();
  const existingIndex = records.findIndex(r => r.employeeId === employeeId && r.date === today);
  
  if (existingIndex !== -1) {
    const existing = records[existingIndex];
    const updated: AttendanceRecord = {
      ...existing,
      ...updates,
    };
    
    if (updated.inTime && updated.outTime) {
      updated.workingHours = calculateWorkingHours(updated.inTime, updated.outTime);
      if (updated.autoGenerated) {
        updated.status = getAutoStatus(updated.inTime, updated.workingHours, officeStartTime);
      }
    }
    
    records[existingIndex] = updated;
    localStorage.setItem(STORAGE_KEY, JSON.stringify(records));
    return updated;
  } else {
    const newRecord: AttendanceRecord = {
      id: crypto.randomUUID(),
      employeeId,
      employeeName,
      employeeIdNumber,
      designation,
      date: today,
      inTime: "",
      outTime: "",
      workingHours: 0,
      status: "Absent",
      createdAt: new Date().toISOString(),
      autoGenerated: true,
      ...updates,
    };
    
    if (newRecord.inTime && newRecord.outTime) {
      newRecord.workingHours = calculateWorkingHours(newRecord.inTime, newRecord.outTime);
    }
    
    if (newRecord.inTime && newRecord.autoGenerated) {
      newRecord.status = getAutoStatus(newRecord.inTime, newRecord.workingHours, officeStartTime);
    }
    
    records.push(newRecord);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(records));
    return newRecord;
  }
}

export function recordCheckIn(
  employeeId: string,
  employeeName: string,
  employeeIdNumber: string,
  designation: string,
  officeStartTime: string = "08:00"
): AttendanceRecord | null {
  // Check if check-in already exists for today
  const todayRecord = getTodayAttendanceRecord(employeeId);
  
  // Only record check-in if inTime is not already set for today
  if (todayRecord && todayRecord.inTime) {
    return null; // Already checked in today, don't record again
  }
  
  const now = new Date();
  const checkInTime = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;
  
  return createOrUpdateAttendanceRecord(
    employeeId,
    employeeName,
    employeeIdNumber,
    designation,
    { inTime: checkInTime },
    officeStartTime
  );
}

export function recordCheckOut(
  employeeId: string,
  employeeName: string,
  employeeIdNumber: string,
  designation: string,
  officeStartTime: string = "08:00"
): AttendanceRecord {
  const now = new Date();
  const checkOutTime = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;
  
  return createOrUpdateAttendanceRecord(
    employeeId,
    employeeName,
    employeeIdNumber,
    designation,
    { outTime: checkOutTime },
    officeStartTime
  );
}
